plugins {
    alias(libs.plugins.androidApplication)
}

android {
    namespace 'com.example.polinav3'
    //noinspection GradleDependency
    compileSdk 31

    defaultConfig {
        applicationId "com.example.polinav3"
        minSdk 23
        //noinspection ExpiredTargetSdkVersion
        targetSdk 31
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    aaptOptions {
        noCompress "tflite"
    }
    task cleanAppleDoubleFiles(type: Exec) {
        description = 'Cleans AppleDouble files (._*) from the project directory before building.'
        commandLine 'dot_clean', '.'
    }

    preBuild.dependsOn cleanAppleDoubleFiles
}

dependencies {
    implementation libs.appcompat
    implementation libs.material
    implementation libs.constraintlayout
    implementation libs.activity

    implementation libs.gson

    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core

    implementation libs.tensorflow.lite
}

